
# Cancela coleta de dados de telemetria
[browser]
gatherUsageStats = false

# Configurações de tema
[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
base="light"